name: CI

on:
  pull_request:
    types: [opened, synchronize]
  push:
    branches:
      - main

env:
  FORCE_COLOR: true

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - uses: actions/checkout@v4.1.7

      - name: Setup PNPM
        uses: pnpm/action-setup@v4.0.0

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 18
          cache: pnpm

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm build

      - name: Test
        run: pnpm test

      - name: Lint
        run: pnpm lint

      - name: TypeCheck
        run: pnpm typecheck
